### PR TITLE
fix: emoji picker and page icon design spec violations (#186)

### LINKED ISSUE #186: bug: UI does not match design spec after PR #185
## Context

PR #185 (`feat: add page icon emoji picker`) introduced `src/components/emoji-picker.tsx` and `src/components/page-icon.tsx`. Several elements do not match the design spec (`.agents/design.md`).

### 1. Touch targets below 44px minimum (Responsive Behavior)

**Spec:** "Touch targets: minimum 44px on mobile."

| Element | File | Line | Actual | Required |
|---|---|---|---|---|
| Page icon button | `src/components/page-icon.tsx` | 60 | `h-9 w-9` (36px) | ≥44px on mobile |
| Emoji buttons | `src/components/emoji-picker.tsx` | 207 | `h-8 w-8` (32px) | ≥44px on mobile |

**Fix:** Use responsive sizing — e.g. `h-9 w-9 sm:h-9 sm:w-9` on desktop but `min-h-[44px] min-w-[44px]` on mobile, or increase base size to 44px.

### 2. Filter input missing border and focus ring (Inputs)

**Spec:** Inputs should have `border-white/[0.06]` border and `ring-2 ring-ring` on focus.

- **File:** `src/components/emoji-picker.tsx`, line 192
- **Actual:** `outline-none` with no border and no focus ring
- **Expected:** `border border-white/[0.06]` and `focus:ring-2 focus:ring-ring`

### 3. Page icon button invisible on mobile when no icon is set (Responsive Behavior / Accessibility)

**Spec:** Touch targets must be accessible on mobile. "No horizontal scroll on any breakpoint."

- **File:** `src/components/page-icon.tsx`, line 65
- **Actual:** `opacity-0 group-hover/page-icon:opacity-100` — relies on hover, which doesn't exist on touch devices. When no icon is set, the button is permanently invisible on mobile.
- **Expected:** The button should be visible on mobile (e.g. `opacity-0 group-hover/page-icon:opacity-100 sm:opacity-0 max-sm:opacity-100` or always show a subtle placeholder on touch).

### 4. Emoji picker clips on mobile viewport (Responsive Behavior)

**Spec:** "No horizontal scroll on any breakpoint."

- **File:** `src/components/emoji-picker.tsx`, line 186
- **Actual:** The picker is `w-72` (288px) and positioned with `shift({ padding: 8 })`, but on 375px mobile viewport the rightmost emoji column is clipped/cut off when the picker is positioned near the left edge.
- **Expected:** Picker should be fully visible within the viewport on all breakpoints. Consider reducing width on mobile or adjusting the shift padding.

## Screenshots

Visual verification was performed against `https://memo.software-factory.dev` on desktop (1280×800) and mobile (375×812) viewports in dark mode. Violations 3 and 4 were confirmed visually.

### PR DESCRIPTION
**Pull request by zacharias-ona**
Closes #186

## What

The emoji picker and page icon components introduced in PR #185 had four design spec violations: emoji buttons and page icon buttons had touch targets below the 44px mobile minimum, the filter input was missing its border and focus ring, the "Add icon" button was invisible on mobile (hover-only opacity), and the emoji picker clipped on narrow mobile viewports.

## How

Applied responsive Tailwind classes to enforce 44px minimum touch targets on mobile while preserving desktop sizes. Added `border border-white/[0.06]` and `focus:ring-2 focus:ring-ring` to the filter input per the input spec. Made the "Add icon" button visible on mobile with `max-sm:opacity-100`. Changed the picker width from fixed `w-72` to `w-[calc(100vw-16px)] sm:w-72` so it fits within narrow viewports.

## Testing

Added 7 static analysis regression tests in `src/components/emoji-picker-design-spec.test.ts` that verify:
- Emoji buttons have 44px minimum touch targets
- Filter input has border and focus ring classes
- Picker uses responsive width to avoid mobile clipping
- Page icon button has 44px minimum touch targets
- "Add icon" button is visible on mobile (not hover-only)

All 220 tests pass. Lint and typecheck clean.

### CODE REVIEW

**Comment by zacharias-ona** [comment]
[ci-fix] This PR has failed CI 3+ times. Needs human investigation.

**Root cause:** The `staging` job (`supabase db reset --linked --yes`) fails because the migration `20260417165531_create_page_images_bucket.sql` on this branch uses a non-idempotent `INSERT` — the `page-images` bucket already exists in the staging Supabase project.

This branch has the old version of the migration (plain `INSERT` and `CREATE POLICY` without conflict handling). `main` was updated in `5b88785` to use `ON CONFLICT (id) DO NOTHING` and `DO $$ BEGIN ... EXCEPTION WHEN duplicate_object` wrappers.

**Fix:** Rebase the branch onto current `main`, or update `supabase/migrations/20260417165531_create_page_images_bucket.sql` on this branch to match the idempotent version on `main`.

**Comment by zacharias-ona** [comment]
[shepherd:conflict] Rebased on main but checks fail. The rebase resolves the merge conflict in `src/components/page-icon.tsx` (additive — mobile visibility classes), but a design spec test added on `main` (`src/components/page-icon-design-spec.test.ts` from issue #191) asserts that the hover-reveal wrapper must NOT use `transition-opacity`. This PR intentionally adds `transition-opacity` for the mobile visibility fix.

This is a genuine semantic conflict between two design decisions:
- **Issue #191** (on main): "Hover states: no transition (instant)" — enforced by the test
- **Issue #186** (this PR): Adds `transition-opacity` for smooth mobile visibility

A human needs to decide which behavior is correct, or update the test to allow `transition-opacity` on mobile.

Conflicting files: `src/components/page-icon.tsx`, `src/components/page-icon-design-spec.test.ts`

File: src/components/emoji-picker.tsx [hunk 1]
```diff
@@ -213,7 +213,7 @@ export function EmojiPicker({
                     <button
                       key={emoji}
                       onClick={() => handleSelect(emoji)}
-                      className="flex h-8 w-8 items-center justify-center text-lg hover:bg-white/[0.04]"
+                      className="flex min-h-[44px] min-w-[44px] items-center justify-center text-lg hover:bg-white/[0.04] sm:min-h-8 sm:min-w-8"
```
Comment (zacharias-ona) [inline src/components/emoji-picker.tsx:216]: The emoji buttons now have `min-w-[44px]` on mobile, but the grid is still `grid-cols-8`. On a 375px viewport the picker is `calc(100vw - 16px)` = 359px, minus `p-2` (16px) = 343px of usable grid space. 8 columns × 44px = 352px (before gaps), which overflows.

Fix: make the grid responsive — fewer columns on mobile so the 44px targets fit:

```tsx
<div className="grid grid-cols-6 gap-0.5 sm:grid-cols-8">
```

6 × 44px = 264px fits comfortably within 343px on mobile, and desktop keeps the original 8-column layout.

**Comment by zacharias-ona** [comment]
**Review: 1 blocking issue found**

The PR correctly addresses all four violations from issue #186 — touch targets, input styling, mobile visibility, and responsive picker width.

**Blocking:**
1. **Emoji grid overflows on mobile**: The grid remains `grid-cols-8` but emoji buttons now have `min-w-[44px]`. On a 375px viewport, 8 × 44px exceeds the available picker width. The grid needs responsive columns (e.g., `grid-cols-6 sm:grid-cols-8`). See inline comment.

Pushing a fix for this now.

**Comment by zacharias-ona** [comment]
⚠️ UI verification found design spec violations. See #201.

**Static analysis:** 3 instances of arbitrary spacing values (`min-h-[44px]`, `min-w-[44px]`) where Tailwind scale equivalents exist (`min-h-11`, `min-w-11`). The design spec prohibits arbitrary spacing when a scale class matches.

**Visual verification:** ✅ No visual regressions. Emoji picker renders correctly on desktop (8-col grid) and mobile (6-col grid, full-width). Filter input has border and focus ring. "Add icon" button visible on mobile. Touch targets adequate. No clipping or overflow.

**Comment by zacharias-ona** [comment]
✅ Post-merge verification passed.

**E2E suite**: 46/47 passed. The 1 failure (`search with no matches shows empty state`) is a known pre-existing issue (#144), unrelated to this PR's emoji picker/page icon changes.

**Ad-hoc smoke tests** (all passed):
- Landing page — loaded, title present
- `/sign-in` — rendered with email input
- `/api/health` — healthy
- Authenticated flow — login succeeded, workspace loaded
- No console errors (unauthenticated or authenticated)

**Skipped**:
- `/dashboard` (not yet built)
- Editor page navigation (no page buttons found in test workspace)
