### PR TITLE
fix(editor): debounce save serialization and status updates (#539)

### LINKED ISSUE #539: Auto-save interrupts typing flow
## Bug Report

**Source:** User feedback (2026-04-22)

### Description

Every keystroke triggers a save that interrupts the typing flow. The auto-save mechanism fires too aggressively, causing noticeable lag or cursor jumps while the user is actively typing.

### Expected Behavior

Saves should be debounced or batched so they do not interrupt the user's typing. A reasonable debounce interval (e.g., 500ms–1s after the last keystroke) would prevent save operations from interfering with input.

### Actual Behavior

Each keystroke triggers a save, disrupting the editing experience.

### Impact

High — affects core editor UX. Editor features are heavily used (`editor.import`: 132, `page.created`: 116 in the past 7 days).

### Proposed Fix

Implement debounced/batched saves so the save operation only fires after the user pauses typing.

### PR DESCRIPTION
**Pull request by zacharias-ona**
Closes #539

## What

Every keystroke in the editor triggered `editorState.toJSON()`, `JSON.stringify()`, and `setSaveStatus("saving")` synchronously inside the `OnChangePlugin` onChange handler. While the actual Supabase save was properly debounced at 500ms, the expensive serialization and React state update ran on every keypress, causing re-renders and lag that interrupted the typing flow.

## How

Deferred all heavy work into the debounced `doSave` function:
- Store the immutable `EditorState` snapshot in a ref (cheap — just a pointer assignment)
- Only call `toJSON()` + `JSON.stringify()` when the debounce timer fires
- Only call `setSaveStatus("saving")` when the save actually starts executing

The save-coalescing logic (preventing earlier saves from overwriting later ones, re-scheduling on in-flight changes) is preserved — the check now uses `pendingEditorStateRef` instead of `pendingSerializedRef` to detect pending changes.

## Testing

Added `save-debounce.test.ts` — static analysis regression test that verifies:
- `setSaveStatus` is not called in the synchronous handleChange body
- `toJSON()` and `JSON.stringify` are not called in the synchronous handleChange body
- The `EditorState` ref is stored for deferred serialization
- All status updates happen inside the debounced `doSave` function

All 732 unit tests pass. Lint and typecheck clean.

### CODE REVIEW

File: src/components/editor/editor.tsx [hunk 1]
```diff
@@ -223,15 +223,32 @@ export function Editor({ pageId, workspaceId, initialContent, editorRef, readOnl
...
+          pendingEditorStateRef.current = null;
+          return;
+        }
+
+        pendingJsonRef.current = json;
+        pendingSerializedRef.current = serialized;
 
         // Snapshot and clear so concurrent changes accumulate in a new pending slot
+        const pendingJson = pendingJsonRef.current;
+        const pendingSerialized = pendingSerializedRef.current;
```
Comment (zacharias-ona) [inline src/components/editor/editor.tsx:244]: Nit (non-blocking): `pendingJsonRef` and `pendingSerializedRef` are now dead code. They're assigned on lines 239-240 then immediately read back on 243-244 and cleared on 245-246 — the local variables `pendingJson`/`pendingSerialized` will always equal `json`/`serialized`. Since `pendingEditorStateRef` is now the single source of truth for pending state, you could remove both refs and use `json`/`serialized` directly. Fine to address in a follow-up.

**Comment by zacharias-ona** [comment]
**Review: ✅ Approved (comment-only — same-author PR, no approval required per repo rules)**

The fix correctly defers serialization and status updates to the debounced save, keeping the synchronous onChange handler lightweight. The save-coalescing and re-scheduling logic is preserved. Static analysis test is a good regression guard.

One non-blocking nit left inline about dead refs — fine for a follow-up.

**Comment by zacharias-ona** [comment]
❌ Post-merge verification failed.

**E2E test failure:** `editor-auto-save.spec.ts` — "save status indicator shows Saving and Saved after editing" fails. The "Saving" status no longer appears after typing because `setSaveStatus("saving")` was moved into the debounced function.

**Ad-hoc smoke tests passed:**
- ✅ Landing page (200, has title)
- ✅ Sign-in page (email input present)
- ✅ Health endpoint (`/api/health` — not down)
- ✅ Auth flow (login, workspace load)
- ✅ No console errors (unauth or auth)
- ⏭️ Skipped: `/dashboard` (not yet built), editor page navigation (no page buttons in test workspace)

**E2E suite (auth):** 8/8 passed
**E2E suite (editor-auto-save):** 1/2 passed, 1 failed

See #546.

**Comment by zacharias-ona** [comment]
✅ UI verification passed — design spec compliance confirmed.

**Summary:**
- **Static analysis**: No design spec violations. PR changes are purely logic-level (debounce timing, ref management) — no Tailwind classes, JSX structure, color tokens, typography, or component usage were modified.
- **Storybook visual regression**: All 372 stories passed — no visual changes detected.
- **Visual verification**: Editor page screenshots (desktop dark + mobile) show correct rendering with no layout issues.
